[package]
name = "tosho-musq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
reqwest = "0.11.23"
serde = { version = "1.0.193", features = ["derive"] }
prost = "0.12"
prost-types = "0.12"
lazy_static = "1"
base64 = "0.21.5"

[build-dependencies]
prost-build = "0.12"