name: CI
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
  merge_group:
  workflow_dispatch:
    inputs:
      release_build:
        description: 'Create the release build without publishing'
        required: true
        type: boolean
        default: false
      no_updater:
        description: 'Build without the self-updater feature'
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-26.04
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') || !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22
        with:
          submodules: 'true'

      - name: Rustup stable
        run: |
          rustup update stable
          echo "RUST_VERSION=$(rustc --version | cut -d ' ' -f 2)" >> "$GITHUB_ENV"

      - name: Setup rust cache
        uses: Swatinem/rust-cache@baf1a810e98b6a3001d0d7234864ed75a17c42fb
        with:
          prefix-key: "rust-tosho-tests-${{ runner.os }}-${{ env.RUST_VERSION }}"

      - name: Test
        run: cargo test --verbose --all

  build:
    strategy:
      matrix:
        os:
          # Linux (x64)
          - [ubuntu-26.04, x86_64-unknown-linux-gnu]
          # Linux (ARM64)
          - [ubuntu-26.04-arm, aarch64-unknown-linux-gnu]
          # macOS Apple Intel (Sonoma)
          - [macos-26-intel, x86_64-apple-darwin]
          # macOS Apple Silicon (Tahoe)
          - [macos-26, aarch64-apple-darwin]
          # Windows Server 2025 (x64)
          - [windows-2025, x86_64-pc-windows-msvc]
          # Windows 11 ARM (ARM64)
          - [windows-11-arm, aarch64-pc-windows-msvc]
          # Android via Ubuntu
          - [ubuntu-26.04, android-build]
      fail-fast: false

    runs-on: ${{ matrix.os[0] }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22

      - name: Rust Target
        if: matrix.os[1] != 'android-build'
        run: |
          rustup update stable
          rustup target add ${{ matrix.os[1] }}

      - name: Rust Target (Android)
        if: matrix.os[1] == 'android-build'
        run: |
          rustup update stable
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi

      # In here, we set up the rust version used, the build mode (release or nightly/debug)
      # We can check for relase mode by checking refs/tags/v* or input.release_build
      - name: Set up cache tag
        run: |
          echo "RUST_VERSION=$(rustc --version | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
          if [ ${{ startsWith(github.ref, 'refs/tags/v') }} = true ] || [ ${{ inputs.release_build == true }} = true ]; then
            echo "BUILD_PROFILE=release" >> "$GITHUB_ENV"
          else
            echo "BUILD_PROFILE=debug" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Setup rust cache
        uses: Swatinem/rust-cache@baf1a810e98b6a3001d0d7234864ed75a17c42fb
        with:
          prefix-key: "rust-tosho-build-${{ env.BUILD_PROFILE }}-${{ runner.os }}-${{ matrix.os[1] }}-${{ env.RUST_VERSION }}"

      - name: Setup Android NDK
        if: matrix.os[1] == 'android-build'
        id: ndk
        uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Configure linker (Android)
        if: matrix.os[1] == 'android-build'
        run: |
          mkdir -p .cargo

          cat > .cargo/config.toml <<EOF
          [target.aarch64-linux-android]
          linker = "${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"

          [target.armv7-linux-androideabi]
          linker = "${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"
          EOF

      - name: Build (Nightly)
        if: env.BUILD_PROFILE == 'debug' && matrix.os[1] != 'android-build'
        run: |
          if [ ${{ inputs.no_updater == true }} = true ]; then
            echo "Building without self-updater feature"
            cargo build --locked --verbose --bin tosho --target ${{ matrix.os[1] }} --profile ci --no-default-features
          else
            echo "Building with self-updater feature"
            cargo build --locked --verbose --bin tosho --target ${{ matrix.os[1] }} --profile ci
          fi
        shell: bash

      - name: Build (Nightly-Android)
        if: env.BUILD_PROFILE == 'debug' && matrix.os[1] == 'android-build'
        run: |
          export PATH="${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
          if [ ${{ inputs.no_updater == true }} = true ]; then
            echo "Building without self-updater feature"
            cargo build --locked --verbose --bin tosho --target aarch64-linux-android --profile ci --no-default-features
            cargo build --locked --verbose --bin tosho --target armv7-linux-androideabi --profile ci --no-default-features
          else
            echo "Building with self-updater feature"
            cargo build --locked --verbose --bin tosho --target aarch64-linux-android --profile ci
            cargo build --locked --verbose --bin tosho --target armv7-linux-androideabi --profile ci
          fi
        shell: bash
        env:
          CC_aarch64_linux_android: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          AR_aarch64_linux_android: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          CC_armv7_linux_androideabi: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
          AR_armv7_linux_androideabi: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar

      - name: Permissions (Nightly)
        if: env.BUILD_PROFILE == 'debug' && runner.os != 'Windows' && matrix.os[1] != 'android-build'
        run: |
          chmod +x target/${{ matrix.os[1] }}/ci/tosho
        shell: bash

      - name: Permissions (Nightly-Android)
        if: env.BUILD_PROFILE == 'debug' && runner.os != 'Windows' && matrix.os[1] == 'android-build'
        run: |
          chmod +x target/aarch64-linux-android/ci/tosho
          chmod +x target/armv7-linux-androideabi/ci/tosho

          # Move both file to android-build folder
          mkdir -p target/android-build/ci
          mv target/aarch64-linux-android/ci/tosho target/android-build/ci/tosho-aarch64
          mv target/armv7-linux-androideabi/ci/tosho target/android-build/ci/tosho-armv7
          chmod +x target/android-build/ci/tosho-aarch64
          chmod +x target/android-build/ci/tosho-armv7
        shell: bash

      - name: Upload artifact
        if: env.BUILD_PROFILE == 'debug'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: tosho-${{ matrix.os[1] }}
          path: |
            target/${{ matrix.os[1] }}/ci/tosho.exe
            target/${{ matrix.os[1] }}/ci/tosho
            target/android-build/ci/tosho-aarch64
            target/android-build/ci/tosho-armv7

      - name: Build (Release)
        if: env.BUILD_PROFILE == 'release' && matrix.os[1] != 'android-build'
        run: |
          if [ ${{ inputs.no_updater == true }} = true ]; then
            echo "Building without self-updater feature"
            cargo build --locked --verbose --bin tosho --target ${{ matrix.os[1] }} --profile ci --no-default-features
          else
            echo "Building with self-updater feature"
            cargo build --locked --verbose --bin tosho --target ${{ matrix.os[1] }} --profile ci
          fi
        shell: bash
        env:
          RELEASE: true

      - name: Build (Release-Android)
        if: env.BUILD_PROFILE == 'release' && matrix.os[1] == 'android-build'
        run: |
          export PATH="${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
          if [ ${{ inputs.no_updater == true }} = true ]; then
            echo "Building without self-updater feature"
            cargo build --locked --verbose --bin tosho --target aarch64-linux-android --profile ci --no-default-features
            cargo build --locked --verbose --bin tosho --target armv7-linux-androideabi --profile ci --no-default-features
          else
            echo "Building with self-updater feature"
            cargo build --locked --verbose --bin tosho --target aarch64-linux-android --profile ci
            cargo build --locked --verbose --bin tosho --target armv7-linux-androideabi --profile ci
          fi
        shell: bash
        env:
          RELEASE: true
          CC_aarch64_linux_android: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          AR_aarch64_linux_android: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          CC_armv7_linux_androideabi: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
          AR_armv7_linux_androideabi: ${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar

      - name: Prepare release
        if: env.BUILD_PROFILE == 'release' && runner.os != 'Windows' && matrix.os[1] != 'android-build'
        shell: bash
        run: |
          cd target/${{ matrix.os[1] }}/ci
          chmod +x tosho
          tar -czvf tosho-${{ matrix.os[1] }}.tar.gz tosho
          mv tosho-${{ matrix.os[1] }}.tar.gz ../../..
          cd ../../..

      - name: Prepare release (Android)
        if: env.BUILD_PROFILE == 'release' && runner.os != 'Windows' && matrix.os[1] == 'android-build'
        shell: bash
        run: |
          mkdir -p target/android-build/ci
          mv target/aarch64-linux-android/ci/tosho target/android-build/ci/tosho-aarch64
          mv target/armv7-linux-androideabi/ci/tosho target/android-build/ci/tosho-armv7
          chmod +x target/android-build/ci/tosho-aarch64
          chmod +x target/android-build/ci/tosho-armv7
          cd target/android-build/ci
          tar -czvf tosho-${{ matrix.os[1] }}.tar.gz tosho-aarch64 tosho-armv7
          mv tosho-${{ matrix.os[1] }}.tar.gz ../../..
          cd ../../..

      - name: Prepare release (Win32)
        if: env.BUILD_PROFILE == 'release' && runner.os == 'Windows'
        run: |
          cd target/${{ matrix.os[1] }}/ci
          Compress-Archive -Path tosho.exe -DestinationPath tosho-${{ matrix.os[1] }}.zip
          mv tosho-${{ matrix.os[1] }}.zip ../../..
          cd ../../..
        shell: powershell

      - name: Upload artifact (Release)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: env.BUILD_PROFILE == 'release'
        with:
          name: tosho-packages-${{ matrix.os[1] }}
          path: |
            tosho-${{ matrix.os[1] }}.zip
            tosho-${{ matrix.os[1] }}.tar.gz

  releases:
    runs-on: ubuntu-26.04
    needs: [tests, build]
    if: startsWith(github.ref, 'refs/tags/v') && github.repository_owner == 'noaione'
    permissions:
      # Use to sign the release artifacts
      id-token: write
      # Used to upload release assets
      contents: write
      # Used to create discussion posts
      discussions: write
      # Used to generate artifact attestation
      attestations: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22

      - name: Download artifacts
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          path: tosho-packages
          pattern: tosho-packages-*
          merge-multiple: true

      - name: Generate artifacts attestation
        uses: actions/attest-build-provenance@f14352a605c57b0a66e0d49bba5825967f1dbedf
        id: attest
        with:
          subject-path: tosho-packages/*

      - name: Create changelog
        id: prepare-change
        run: |
          python3 scripts/create_changelog.py
          # Fetch git tag contents subject
          VERSION_SUBJ=$(git tag -l --format='%(contents:subject)' ${{ github.ref }})
          echo "version_subject=$VERSION_SUBJ" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ github.ref }}
          ATTEST_URL: ${{ steps.attest.outputs.attestation-url }}

      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          files: |
            tosho-packages/*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG-GENERATED.md
          name: ${{ steps.prepare-change.outputs.version_subject }}

      - name: Create discussions
        uses: nvdaes/build-discussion@2b1aa4c0c61edf44580576e491af5219be2b8ca6
        with:
          title: Release ${{ github.ref_name }}
          body: |
            Release **${{ github.ref_name }}** is now available for **[download](https://github.com/noaione/tosho-mango/releases/tag/${{ github.ref_name }})**.

            Please see the [changelog](https://github.com/noaione/tosho-mango/blob/master/CHANGELOG.md) for more information.

            Report any issues you found in the [issue tracker](https://github.com/noaione/tosho-mango/issues/new/choose)
          category-position: 1  # Announcements
