name: Lint
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
      - 'scripts/**'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
      - 'scripts/**'
  merge_group:

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') || !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22

      - name: Setup rust cache
        uses: Swatinem/rust-cache@baf1a810e98b6a3001d0d7234864ed75a17c42fb
        with:
          prefix-key: "rust-tosho-lint-${{ runner.os }}"

      - name: Lint
        run: cargo clippy --verbose --all -- -D warnings
